<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class DestroyCrud extends Command
{
    protected $signature = 'destroy:crud
                            {name : Table name (same as used in make:crud)}
                            {--route= : Custom route name (same as used in make:crud)}
                            {--force : Skip confirmation prompt}';

    protected $description = 'Delete all files generated by make:crud {name} livewire';

    public function __construct(protected Filesystem $files)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $table = $this->argument('name');
        $modelName = Str::studly(Str::singular($table));
        $route = $this->option('route') ?? Str::kebab(Str::plural($modelName));
        $pluralUpper = ucfirst(Str::plural($modelName));
        $modelKebab = Str::kebab($modelName);

        $livewireNs = config('crud.livewire.namespace', 'App\Livewire');
        $livewirePath = $this->namespacePath($livewireNs);
        $modelNs = config('crud.model.namespace', 'App\Models');
        $modelPath = $this->namespacePath($modelNs);
        $requestNs = config('crud.request.namespace', 'App\Http\Requests');
        $requestPath = $this->namespacePath($requestNs);

        $files = [
            app_path("{$modelPath}{$modelName}.php"),
            app_path("{$requestPath}{$modelName}Request.php"),
            app_path("{$livewirePath}{$pluralUpper}/Index.php"),
            app_path("{$livewirePath}{$pluralUpper}/Show.php"),
            app_path("{$livewirePath}{$pluralUpper}/Edit.php"),
            app_path("{$livewirePath}{$pluralUpper}/Create.php"),
            app_path("{$livewirePath}Forms/{$modelName}Form.php"),
        ];

        $viewDir = resource_path("views/livewire/{$modelKebab}");
        $viewFiles = [
            "{$viewDir}/index.blade.php",
            "{$viewDir}/create.blade.php",
            "{$viewDir}/edit.blade.php",
            "{$viewDir}/form.blade.php",
            "{$viewDir}/show.blade.php",
        ];

        $existing = array_filter(
            array_merge($files, $viewFiles),
            fn ($path) => $this->files->exists($path)
        );

        if (empty($existing)) {
            $this->warn("No files found for model [{$modelName}].");

            return self::SUCCESS;
        }

        $this->line("Files to delete for <info>{$modelName}</info>:");
        foreach ($existing as $path) {
            $this->line('  - '.$this->relativePath($path));
        }

        if (! $this->option('force') && ! $this->confirm('Delete all listed files?', false)) {
            $this->info('Aborted.');

            return self::SUCCESS;
        }

        foreach ($existing as $path) {
            $this->files->delete($path);
            $this->line('  <fg=red>Deleted:</> '.$this->relativePath($path));
        }

        $this->deleteDirectoryIfEmpty(app_path("{$livewirePath}{$pluralUpper}"));
        $this->deleteDirectoryIfEmpty($viewDir);

        $this->newLine();
        $this->info('Done. Remember to remove the route group for ['.$route.'] from routes/web.php.');

        return self::SUCCESS;
    }

    private function deleteDirectoryIfEmpty(string $dir): void
    {
        if ($this->files->isDirectory($dir) && empty($this->files->files($dir)) && empty($this->files->directories($dir))) {
            $this->files->deleteDirectory($dir);
            $this->line('  <fg=red>Deleted dir:</> '.$this->relativePath($dir));
        }
    }

    private function namespacePath(string $namespace): string
    {
        $str = Str::finish(Str::after($namespace, 'App\\'), '\\');

        return str_replace('\\', '/', $str);
    }

    private function relativePath(string $path): string
    {
        $base = str_replace('\\', '/', base_path());
        $path = str_replace('\\', '/', $path);

        return ltrim(str_replace($base, '', $path), '/');
    }
}
